<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Confirm
 * @package App
 *
 * @property integer $id
 * @property integer $type
 * @property string $object
 * @property boolean $is_confirmed
 * @property integer $send_count
 * @property integer $try_count
 * @property integer $created_at
 * @property integer $updated_at
 */
class Confirm extends Model
{
    protected $connection = 'pgsql';
    protected $table = 'confirm_object';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [];

    public function codes()
    {
        return $this->hasMany(Code::class, 'object_id', 'id');
    }

    public function toJson($options = 0)
    {
        return parent::toJson($options); // TODO: Change the autogenerated stub
    }
}
